spring.application.name=AuthService
spring.datasource.url=jdbc:postgresql://localhost:5432/authdb
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=9090
jwt.secret=mySuperSecretKey_12345!@#ABCxyz98765
jwt.expiration=3600000